package com.anshtya.fooddelivery.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF9F4200)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDBCB)
val light_onPrimaryContainer = Color(0xFF341100)
val light_secondary = Color(0xFF765849)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFFFDBCB)
val light_onSecondaryContainer = Color(0xFF2C160B)
val light_tertiary = Color(0xFF8D4F00)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFDCC0)
val light_onTertiaryContainer = Color(0xFF2D1600)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF201A18)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF201A18)
val light_surfaceVariant = Color(0xFFF4DED5)
val light_onSurfaceVariant = Color(0xFF52443D)
val light_outline = Color(0xFF85736C)
val light_inverseOnSurface = Color(0xFFFBEEE9)
val light_inverseSurface = Color(0xFF362F2C)
val light_inversePrimary = Color(0xFFFFB692)
//val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF9F4200)
val light_outlineVariant = Color(0xFFD7C2B9)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFFFB692)
val dark_onPrimary = Color(0xFF552000)
val dark_primaryContainer = Color(0xFF793100)
val dark_onPrimaryContainer = Color(0xFFFFDBCB)
val dark_secondary = Color(0xFFE6BEAC)
val dark_onSecondary = Color(0xFF432A1E)
val dark_secondaryContainer = Color(0xFF5C4033)
val dark_onSecondaryContainer = Color(0xFFFFDBCB)
val dark_tertiary = Color(0xFFFFB877)
val dark_onTertiary = Color(0xFF4B2700)
val dark_tertiaryContainer = Color(0xFF6B3B00)
val dark_onTertiaryContainer = Color(0xFFFFDCC0)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF201A18)
val dark_onBackground = Color(0xFFEDE0DB)
val dark_surface = Color(0xFF201A18)
val dark_onSurface = Color(0xFFEDE0DB)
val dark_surfaceVariant = Color(0xFF52443D)
val dark_onSurfaceVariant = Color(0xFFD7C2B9)
val dark_outline = Color(0xFFA08D85)
val dark_inverseOnSurface = Color(0xFF201A18)
val dark_inverseSurface = Color(0xFFEDE0DB)
val dark_inversePrimary = Color(0xFF9F4200)
//val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFFFB692)
val dark_outlineVariant = Color(0xFF52443D)
val dark_scrim = Color(0xFF000000)


val ratingGreenColor = Color(0xFF357A3B)